channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - psutil==5.9.5
  - scikit-learn==1.0.2
  - typing-extensions==4.6.2
name: mlflow-env
