version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install myst-parser poetry
      - poetry -C python-client export --output python-client/requirements.txt --only main
#      - sphinx-apidoc -o python-client/docs python-client/giskard
sphinx:
  configuration: python-client/docs/conf.py

python:
  install:
    - requirements: python-client/requirements.txt
  system_packages: true