version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install pdm
      - pdm export -p python-client --without-hashes -G doc,server -o requirements-sphinx.txt

sphinx:
  configuration: python-client/docs/conf.py

python:
  install:
    - requirements: requirements-sphinx.txt
