version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install myst-parser poetry
      - poetry install -C python-client --only main
#      - sphinx-apidoc -o python-client/docs python-client/giskard
sphinx:
  configuration: python-client/docs/conf.py