version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install poetry
#      - poetry install -C python-client --only main
##      - sphinx-apidoc -o python-client/docs python-client/giskard
    post_create_environment:
      - cd python-client && poetry config virtualenvs.create false
    post_install:
      - cd python-client && poetry install --only main,doc


sphinx:
  configuration: python-client/docs/conf.py

python:
  system_packages: true