channels:
- conda-forge
dependencies:
- python=3.7.16
- pip<=22.0.4
- pip:
  - mlflow<3,>=2.1
  - catboost==1.1.1
  - colorama==0.4.6
  - entrypoints==0.4
  - ipywidgets==8.0.4
  - numpy==1.21.6
  - pandas==1.3.5
  - scipy==1.7.3
name: mlflow-env
