"""rename feedback columns

Revision ID: 5fddce341c39
Revises: 697868f4495c
Create Date: 2021-08-24 17:46:38.248377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fddce341c39'
down_revision = '697868f4495c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'object_name', new_column_name='feature_name')
    op.alter_column('feedbacks', 'object_value', new_column_name='feature_value')
    op.alter_column('feedbacks', 'feedback_type', new_column_name='feedback_choice')
    op.alter_column('feedbacks', 'feedback_object', new_column_name='feedback_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'feature_name', new_column_name='object_name')
    op.alter_column('feedbacks', 'feature_value', new_column_name='object_value')
    op.alter_column('feedbacks', 'feedback_type', new_column_name='feedback_object')
    op.alter_column('feedbacks', 'feedback_choice', new_column_name='feedback_type')
    # ### end Alembic commands ###
