masculine_to_feminine = {
    "he": "she",
    "him": "her",
    "his": "hers",
    "himself": "herself",
    "man": "woman",
    "men": "women",
    "boy": "girl",
    "boys": "girls",
    "father": "mother",
    "dad": "mom",
    "son": "daughter",
    "brother": "sister",
    "uncle": "aunt",
    "nephew": "niece",
    "husband": "wife",
    "groom": "bride",
    "king": "queen",
    "prince": "princess",
    "male": "female",
    "sir": "ma'am",
    "mr.": "ms.",
    "mister": "miss",
    "chairman": "chairwoman",
    "businessman": "businesswoman",
    "congressman": "congresswoman",
    "steward": "stewardess",
    "actor": "actress",
    "waiter": "waitress",
    "policeman": "policewoman",
    "fireman": "firewoman",
    "mailman": "mailwoman",
    "salesman": "saleswoman",
    "spokesman": "spokeswoman",
    "landlord": "landlady",
    "host": "hostess",
    "gentleman": "lady",
    "grandfather": "grandmother",
    "grandpa": "grandma",
    "papa": "mama",
    "daddy": "mommy",
    "son-in-law": "daughter-in-law",
    "brother-in-law": "sister-in-law",
    "father-in-law": "mother-in-law",
    "kingpin": "queenpin",
    "godfather": "godmother",
    "sugar daddy": "sugar mommy"
}

feminine_to_masculine = {
    'she': 'he',
    'her': 'him',
    'hers': 'his',
    'herself': 'himself',
    'woman': 'man',
    'women': 'men',
    'girl': 'boy',
    'girls': 'boys',
    'mother': 'father',
    'mom': 'dad',
    'daughter': 'son',
    'sister': 'brother',
    'aunt': 'uncle',
    'niece': 'nephew',
    'wife': 'husband',
    'bride': 'groom',
    'queen': 'king',
    'princess': 'prince',
    'female': 'male',
    "ma'am": 'sir',
    'ms.': 'mr.',
    'miss': 'mister',
    'chairwoman': 'chairman',
    'businesswoman': 'businessman',
    'congresswoman': 'congressman',
    'stewardess': 'steward',
    'actress': 'actor',
    'waitress': 'waiter',
    'policewoman': 'policeman',
    'firewoman': 'fireman',
    'mailwoman': 'mailman',
    'saleswoman': 'salesman',
    'spokeswoman': 'spokesman',
    'landlady': 'landlord',
    'hostess': 'host',
    'lady': 'gentleman',
    'grandmother': 'grandfather',
    'grandma': 'grandpa',
    'mama': 'papa',
    'mommy': 'daddy',
    'daughter-in-law': 'son-in-law',
    'sister-in-law': 'brother-in-law',
    'mother-in-law': 'father-in-law',
    'queenpin': 'kingpin',
    'godmother': 'godfather',
    'sugar mommy': 'sugar daddy'}

# Modifying the religion_dict using the list of religions from the ethnicity_dict
religion_dict = {
    'religion': ['buddhism',
                 'christianity',
                 'confucianism',
                 'hinduism',
                 'islam',
                 'judaism',
                 'sikhism'],
    'founder': ['siddhartha gautama',
                'jesus christ',
                'confucius',
                'unknown',
                'muhammad',
                'abraham',
                'Guru Nanak'],
    'practitioner': ['buddhist',
                     'christian',
                     'confucian',
                     'hindu',
                     'muslim',
                     'jew',
                     'Sikh'],
    'deity': ['god',
              'jesus',
              'holy spirit',
              'brahma',
              'vishnu',
              'shiva',
              'allah',
              'god',
              'One God (Waheguru)'],
    'place of prayer': ['temple',
                        'church',
                        'temple',
                        'temple',
                        'mosque',
                        'synagogue',
                        'Gurdwara'],
    'known place': ['bodh gaya',
                    'sarnath',
                    'lumbini',
                    'jerusalem',
                    'vatican city',
                    'canterbury cathedral',
                    'temple of confucius',
                    'confucian temple of shanghai',
                    "confucius' family mansion",
                    'varanasi',
                    'haridwar',
                    'ujjain',
                    'mecca',
                    'medina',
                    'al-aqsa mosque',
                    'jerusalem',
                    'western wall',
                    'bethlehem',
                    'Harmandir Sahib (Golden Temple)',
                    'Nankana Sahib'],
    'holy text': ['tripitaka',
                  'mahayana sutra',
                  'bible',
                  'catechism of the catholic church',
                  'book of common prayer',
                  'analects',
                  'mencius',
                  'the great learning',
                  'veda',
                  'upanishad',
                  'bhagavad gita',
                  'quran',
                  'hadith',
                  'tanakh',
                  'talmud',
                  'Guru Granth Sahib'],
    'religious leader': ['dalai lama',
                         'thich nhat hanh',
                         'pope francis',
                         'archbishop of canterbury',
                         'swami vivekananda',
                         'sri sri ravi shankar',
                         'imam',
                         'mufti',
                         'rabbi',
                         'hazzan',
                         'Guru Nanak',
                         'Guru Gobind Singh',
                         'Guru Arjan',
                         'Guru Tegh Bahadur']}

minority_groups = ['african american', 'black', 'hispanic', 'latinx', 'native american', 'indigenous',
                   'asian american', 'pacific islander', 'middle eastern', 'arab', 'south asian', 'desi',
                   'jewish', 'roma', 'romani', 'afro-latinx', 'afro-caribbean', 'afro-asian', 'afro-arab',
                   'indigenous peoples of south america, central america, and the caribbean',
                   'other indigenous peoples', 'mixed', 'multiracial individuals']

typos = {
            'a': ['s', 'z', 'q', 'w', 'x'],
            'b': ['v', 'n', 'g', 'h'],
            'c': ['x', 'v', 'f', 'd'],
            'd': ['s', 'e', 'r', 'f', 'c', 'x'],
            'e': ['w', 's', 'd', 'r'],
            'f': ['d', 'r', 't', 'g', 'v', 'c'],
            'g': ['f', 't', 'y', 'h', 'b', 'v'],
            'h': ['g', 'y', 'u', 'j', 'n', 'b'],
            'i': ['u', 'j', 'k', 'o'],
            'j': ['h', 'u', 'i', 'k', 'm', 'n'],
            'k': ['j', 'i', 'o', 'l', 'm'],
            'l': ['k', 'o', 'p'],
            'm': ['n', 'j', 'k'],
            'n': ['b', 'h', 'j', 'm'],
            'o': ['i', 'k', 'l', 'p'],
            'p': ['o', 'l'],
            'q': ['a', 'w'],
            'r': ['e', 'd', 'f', 't'],
            's': ['a', 'w', 'd', 'x', 'z'],
            't': ['r', 'f', 'g', 'y'],
            'u': ['y', 'h', 'j', 'i'],
            'v': ['c', 'f', 'g', 'b'],
            'w': ['q', 'a', 's', 'e'],
            'x': ['z', 's', 'd', 'c'],
            'y': ['t', 'g', 'h', 'u'],
            'z': ['a', 's', 'x'],
        }