gender_switch_en = {'abbess': 'abbot',
                    'able_seaman': 'able_seawoman',
                    'actress': 'actor',
                    'adulteress': 'adulterer',
                    'adventuress': 'adventurer',
                    'aircraftsman': 'aircraftswoman',
                    'aircrewman': 'aircrewwoman',
                    'alderman': 'alderwoman',
                    'altar_boy': 'altar_girl',
                    'ambassadress': 'ambassador',
                    'ancestress': 'ancestor',
                    'ape-man': 'ape-woman',
                    'archduchess': 'archduke',
                    'artilleryman': 'artillerywoman',
                    'assemblyman': 'assemblywoman',
                    'assemblywoman': 'assemblyman',
                    'au_pair_girl': 'au_pair_boy',
                    'aunt': 'uncle',
                    'authoress': 'author',
                    'aviatrix': 'aviator',
                    'b-girl': 'escort',
                    'bachelor': 'bachelorette',
                    'bachelor_girl': 'bachelor',
                    'backroom_boy': 'backroom_girl',
                    'baggageman': 'baggagewoman',
                    'bagman': 'bagwoman',
                    'ball_boy': 'ball_girl',
                    'ballerina': 'ballet dancer',
                    'bandsman': 'bandswoman',
                    'barmaid': 'barman',
                    'baron': 'baroness',
                    'baroness': 'baron',
                    'bat_boy': 'bat_girl',
                    'batman': 'batwoman',
                    'beadsman': 'beadswoman',
                    'beggarman': 'beggarwoman',
                    'beggarwoman': 'beggarman',
                    'bellboy': 'bellgirl',
                    'benefactress': 'benefactor',
                    'best_man': 'best_woman',
                    'big_sister': 'big brother',
                    'black_man': 'black_woman',
                    'black_woman': 'black_man',
                    'blood_brother': 'blood sister',
                    'boatman': 'boatwoman',
                    'bondman': 'bondwoman',
                    'bondsman': 'bondswoman',
                    'bondwoman': 'bondman',
                    'border_patrolman': 'border_patrolwoman',
                    'boy': 'girl',
                    'boyfriend': 'girlfriend',
                    'brahman': 'brahwoman',
                    'brakeman': 'brakewoman',
                    'bride': 'groom',
                    'bridesmaid': 'groomsman',
                    'broth_of_a_boy': 'broth_of_a_girl',
                    'brother': 'sister',
                    'brownie': 'cub scout',
                    'brunet': 'brunette',
                    'bullyboy': 'bullygirl',
                    'busboy': 'busgirl',
                    'bushman': 'bushwoman',
                    'businessman': 'businesswoman',
                    'businesswoman': 'businessman',
                    'cabin_boy': 'cabin_girl',
                    'call_girl': 'call_boy',
                    'cameraman': 'camerawoman',
                    'campfire_girl': 'campfire_boy',
                    'canary': 'singer',
                    'career_girl': 'career_boy',
                    'career_man': 'career_woman',
                    'cattleman': 'cattlewoman',
                    'cavalryman': 'cavalrywoman',
                    'caveman': 'cavewoman',
                    'chairman_of_the_board': 'chairwoman of the board',
                    'chapman': 'chapwoman',
                    'charwoman': 'charman',
                    'check_girl': 'check_boy',
                    'choirboy': 'choirgirl',
                    'chorus_girl': 'chorus_boy',
                    'city_man': 'city_woman',
                    'clansman': 'clanswoman',
                    'clergyman': 'clergywoman',
                    'co-ed': 'student',
                    'coachman': 'coachwoman',
                    'coalman': 'coalwoman',
                    'coastguardsman': 'coastguardswoman',
                    'coiffeur': 'coiffeuse',
                    'coiffeuse': 'coiffeur',
                    'comedienne': 'comedian',
                    'comfort_woman': 'comfort_man',
                    'committeeman': 'committeewoman',
                    'committeewoman': 'committeeman',
                    'company_man': 'company_woman',
                    'concubine': 'consort',
                    'confidante': 'confidant',
                    'confidence_man': 'confidence_woman',
                    'congressman': 'congresswoman',
                    'cornishman': 'cornishwoman',
                    'cornishwoman': 'cornishman',
                    'councilman': 'councilwoman',
                    'councilwoman': 'councilman',
                    'count': 'countess',
                    'countryman': 'countrywoman',
                    'countrywoman': 'countryman',
                    'cover_girl': 'cover_boy',
                    'cowboy': 'cowgirl',
                    'cowgirl': 'cowboy',
                    'craftsman': 'craftswoman',
                    'crewman': 'crewwoman',
                    'crown_prince': 'crown_princess',
                    'crown_princess': 'heir apparent',
                    'czar': 'czarina',
                    'dad': 'mom',
                    'dairymaid': 'dairyman',
                    'dairyman': 'dairywoman',
                    'dalesman': 'daleswoman',
                    'danseur': 'ballerina',
                    'daughter': 'son',
                    'daughter-in-law': 'son-in-law',
                    'dayboy': 'daygirl',
                    'daygirl': 'dayboy',
                    'deacon': 'deaconess',
                    'deaconess': 'deacon',
                    'deliveryman': 'deliverywoman',
                    'dirty_old_man': 'dirty_old_woman',
                    'divorcee': 'divorcee',
                    'doughboy': 'doughgirl',
                    'draftsman': 'draftswoman',
                    'dragoman': 'dragowoman',
                    'drum_majorette': 'baton twirler',
                    'duenna': 'chaperone',
                    'elder_statesman': 'elder_stateswoman',
                    'embroideress': 'embroiderer',
                    'emperor': 'empress',
                    'empress': 'emperor',
                    'enchantress': 'sorcerer',
                    'end_man': 'end_woman',
                    'englishman': 'englishwoman',
                    'englishwoman': 'englishman',
                    'enlisted_man': 'enlisted_woman',
                    'enlisted_woman': 'enlisted_man',
                    'ent_man': 'ent_woman',
                    'everyman': 'everywoman',
                    'ex-boyfriend': 'ex-girlfriend',
                    'ex-husband': 'ex-wife',
                    'ex-wife': 'ex-husband',
                    'executrix': 'executor',
                    'family_man': 'family_woman',
                    'fancy_man': 'fancy_woman',
                    'farm_boy': 'farm_girl',
                    'farm_girl': 'farm_boy',
                    'farmerette': 'farmer',
                    'father': 'mother',
                    'father-in-law': 'mother-in-law',
                    'female': 'male',
                    'female_aristocrat': 'male aristocrat',
                    'female_child': 'male_child',
                    'female_sibling': 'male sibling',
                    'ferryman': 'ferrywoman',
                    'fireman': 'firewoman',
                    'first_baseman': 'first_basewoman',
                    'fisherman': 'fisherwoman',
                    'flibbertigibbet': 'fool',
                    'flower_girl': 'flower_boy',
                    'footman': 'footwoman',
                    'foreman': 'forewoman',
                    'foremother': 'ancestor',
                    'forewoman': 'foreman',
                    'foster-brother': 'foster-sister',
                    'foster-father': 'foster-mother',
                    'foster-mother': 'foster-father',
                    'foster-sister': 'foster-brother',
                    'foundress': 'founder',
                    'four-minute_man': 'four-minute_woman',
                    'freedman': 'freedwoman',
                    'freeman': 'freewoman',
                    'frenchman': 'frenchwoman',
                    'front_man': 'front_woman',
                    'frontiersman': 'frontierswoman',
                    'frontierswoman': 'frontiersman',
                    'fugleman': 'fuglewoman',
                    'g-man': 'g-woman',
                    'gagman': 'gagwoman',
                    'garbage_man': 'garbage_woman',
                    'gasman': 'gaswoman',
                    'gay_man': 'gay_woman',
                    'gentleman': 'lady',
                    'gentlemen': 'ladies',
                    'gibson_girl': 'gibson_boy',
                    'girl': 'boy',
                    'girl_friday': 'assistant',
                    'girlfriend': 'boyfriend',
                    'goddaughter': 'godson',
                    'godfather': 'godmother',
                    'godmother': 'godfather',
                    'godson': 'goddaughter',
                    'good_old_boy': 'good_old_girl',
                    'governess': 'governor',
                    'granddaughter': 'grandson',
                    'grandfather': 'grandmother',
                    'grandson': 'granddaughter',
                    'great_grandson': 'great granddaughter',
                    'great-aunt': 'great-uncle',
                    'great-nephew': 'great-niece',
                    'grocery_boy': 'grocery_girl',
                    'groom': 'bride',
                    'groomsman': 'groomswoman',
                    'groundsman': 'groundswoman',
                    'guardsman': 'guardswoman',
                    'gunman': 'gunwoman',
                    'guy': 'gal',
                    'half_sister': 'half brother',
                    'handyman': 'handywoman',
                    'hangman': 'hangwoman',
                    'hatchet_man': 'hatchet_woman',
                    'he': 'she',
                    'head_linesman': 'head_lineswoman',
                    'headman': 'headwoman',
                    'headmistress': 'headmaster',
                    'headsman': 'headswoman',
                    'heidelberg_man': 'heidelberg_woman',
                    'heiress': 'heir',
                    'helmsman': 'helmswoman',
                    'her': 'his',
                    'heroine': 'hero',
                    'hers': 'his',
                    'herself': 'himself',
                    'him': 'her',
                    'himself': 'herself',
                    'his': 'her',
                    'holdup_man': 'holdup_woman',
                    'homeboy': 'homegirl',
                    'homegirl': 'homeboy',
                    'honest_woman': 'honest_man',
                    'horseman': 'horsewoman',
                    'horsewoman': 'horseman',
                    'hostess': 'host',
                    'huntress': 'hunter',
                    'husband': 'wife',
                    'iceman': 'icewoman',
                    'idolatress': 'idolater',
                    'inamorata': 'inamorato',
                    'infantryman': 'infantrywoman',
                    'instructress': 'instructor',
                    'irishman': 'irishwoman',
                    'irishwoman': 'irishman',
                    'iron_man': 'iron_woman',
                    'jewess': 'jew',
                    'jilt': 'jilt',
                    'john_doe': 'jane doe',
                    'king': 'queen',
                    'kinsman': 'kinswoman',
                    'kinswoman': 'kinsman',
                    'klansman': 'klanswoman',
                    'lackey': 'servant',
                    'ladies': 'gentlemen',
                    'lady': 'lord',
                    'landlady': 'landlord',
                    'lawman': 'lawwoman',
                    'layman': 'laywoman',
                    'leading_man': 'leading_woman',
                    'letterman': 'letterwoman',
                    'lighterman': 'lighterwoman',
                    'lineman': 'linewoman',
                    'linesman': 'lineswoman',
                    'linkboy': 'linkgirl',
                    'little_brother': 'little sister',
                    'little_sister': 'little brother',
                    'liveryman': 'liverywoman',
                    'lobsterman': 'lobsterwoman',
                    'lollipop_lady': 'crossing guard',
                    'longbowman': 'longbowwoman',
                    'lord': 'lady',
                    'lowerclassman': 'lowerclasswoman',
                    'lumberman': 'lumberwoman',
                    "ma'am": 'sir',
                    'madam': 'sir',
                    'madwoman': 'madman',
                    'maid': 'domestic',
                    'mailman': 'mailwoman',
                    'male': 'female',
                    'male_sibling': 'female sibling',
                    'malik': 'malikah',
                    'mamma': 'pappa',
                    'man': 'woman',
                    'manageress': 'manager',
                    'mannequin': 'model',
                    'marksman': 'markswoman',
                    'masseur': 'masseuse',
                    'matriarch': 'patriarch',
                    'matron': 'warden',
                    'matron_of_honor': 'best man',
                    'mayoress': 'mayor',
                    'mediatrix': 'mediator',
                    'medicine_man': 'medicine_woman',
                    'memsahib': 'sahib',
                    'men': 'women',
                    'messenger_boy': 'messenger_girl',
                    'mestizo': 'mestiza',
                    'middle-aged_man': 'middle-aged_woman',
                    'midshipman': 'midshipwoman',
                    'military_policeman': 'military_policewoman',
                    'militiaman': 'militiawoman',
                    'milkman': 'milkwoman',
                    'mill-girl': 'mill-boy',
                    'millionairess': 'millionaire',
                    'milord': 'milady',
                    'minuteman': 'minutewoman',
                    'miracle_man': 'miracle_woman',
                    'miss': 'mr.',
                    'mistress': 'other man',
                    'monk': 'female monk',
                    'mother': 'father',
                    "mother's_boy": "mother's_girl",
                    "mother's_son": "mother's_daughter",
                    'mr.': 'ms.',
                    'mrs.': 'mr.',
                    'ms.': 'mr.',
                    'muffin_man': 'muffin_woman',
                    'murderess': 'murderer',
                    'muscleman': 'musclewoman',
                    'nabob': 'begum',
                    'nanny': 'manny',
                    'nautch_girl': 'nautch_boy',
                    'negotiatress': 'negotiator',
                    'nephew': 'niece',
                    'newswoman': 'newsman',
                    'niece': 'nephew',
                    'night_watchman': 'night_watchwoman',
                    'nun': 'monk',
                    'oarsman': 'oarswoman',
                    'oarswoman': 'oarsman',
                    'office_boy': 'office_girl',
                    'oilman': 'oilwoman',
                    'oklahoman': 'oklahowoman',
                    'old_boy': 'old_girl',
                    'old_man': 'old_woman',
                    'old_woman': 'old_man',
                    'orangeman': 'orangewoman',
                    'organization_man': 'organization_woman',
                    'ottoman': 'ottowoman',
                    'outdoorsman': 'outdoorswoman',
                    'outdoorswoman': 'outdoorsman',
                    'pachuco': 'pachuca',
                    'paperboy': 'papergirl',
                    'parisienne': 'parisian',
                    'party_girl': 'party_boy',
                    'party_man': 'party_woman',
                    'patroness': 'patron',
                    'piltdown_man': 'piltdown_woman',
                    'pitchman': 'pitchwoman',
                    'placeman': 'placewoman',
                    'plainclothesman': 'plainclotheswoman',
                    'plainsman': 'plainswoman',
                    'plowboy': 'plowgirl',
                    'plowman': 'plowwoman',
                    'poetess': 'poet',
                    'point_man': 'point_woman',
                    'point_woman': 'point_man',
                    'pointsman': 'pointswoman',
                    'police_matron': 'policeman',
                    'policeman': 'policewoman',
                    'poseuse': 'poseur',
                    'posseman': 'possewoman',
                    'poster_boy': 'poster_girl',
                    'poster_girl': 'poster_boy',
                    'postmistress': 'postmaster',
                    'potboy': 'potgirl',
                    'poultryman': 'poultrywoman',
                    'priest': 'priestess',
                    'priestess': 'priest',
                    'prima_donna': 'opera star',
                    'princess': 'prince',
                    'procuress': 'pimp',
                    'property_man': 'property_woman',
                    'prophetess': 'prophet',
                    'proprietress': 'proprietor',
                    'protegee': 'protege',
                    'quarryman': 'quarrywoman',
                    'queen': 'king',
                    'raftsman': 'raftswoman',
                    'remittance_man': 'remittance_woman',
                    'renaissance_man': 'renaissance_woman',
                    'repairman': 'repairwoman',
                    'rifleman': 'riflewoman',
                    'right-hand_man': 'right-hand_woman',
                    'ring_girl': 'ring_boy',
                    'roadman': 'roadwoman',
                    'roman': 'rowoman',
                    'roundsman': 'roundswoman',
                    'salesgirl': 'salesboy',
                    'salesman': 'saleswoman',
                    'sandboy': 'sandgirl',
                    'sandwichman': 'sandwichwoman',
                    'schoolboy': 'schoolgirl',
                    'schoolgirl': 'schoolboy',
                    'schoolman': 'schoolwoman',
                    'schoolmarm': 'schoolteacher',
                    'scotswoman': 'scotsman',
                    'sculptress': 'sculptor',
                    'second_baseman': 'second_basewoman',
                    'section_man': 'section_woman',
                    'seductress': 'seducer',
                    'seedsman': 'seedswoman',
                    'selectman': 'selectwoman',
                    'selectwoman': 'selectman',
                    'senhor': 'senhora',
                    'servant_girl': 'servant_boy',
                    'serviceman': 'servicewoman',
                    'shaheed': 'shahida',
                    'she': 'he',
                    'sheepman': 'sheepwoman',
                    'sheik': 'sheikha',
                    'shepherdess': 'shepherd',
                    'shop_boy': 'shop_girl',
                    'shop_girl': 'shop_boy',
                    'showman': 'showwoman',
                    'sidesman': 'sideswoman',
                    'signalman': 'signalwoman',
                    'sir': 'madam',
                    'sister': 'brother',
                    'sister-in-law': 'brother-in-law',
                    'skivvy': 'domestic servant',
                    'small_businessman': 'small_businesswoman',
                    'son': 'daughter',
                    'son-in-law': 'daughter-in-law',
                    'songstress': 'songster',
                    'soprano': 'singer',
                    'sorceress': 'sorcerer',
                    'soundman': 'soundwoman',
                    'spokesman': 'spokeswoman',
                    'spokeswoman': 'spokesman',
                    'sporting_man': 'sporting_woman',
                    'squaw_man': 'squaw_woman',
                    'stableman': 'stablewoman',
                    'statesman': 'stateswoman',
                    'stateswoman': 'statesman',
                    'stepbrother': 'stepsister',
                    'stepfather': 'stepmother',
                    'stepmother': 'stepfather',
                    'stewardess': 'steward',
                    'stockman': 'stockwoman',
                    'straight_man': 'straight_woman',
                    'strongman': 'strongwoman',
                    'swagman': 'swagwoman',
                    'sweater_girl': 'sweater_boy',
                    't-man': 't-woman',
                    'tallyman': 'tallywoman',
                    'taskmistress': 'taskmaster',
                    'testatrix': 'testator',
                    'third_baseman': 'third_basewoman',
                    'timberman': 'timberwoman',
                    'toast_mistress': 'toastmaster',
                    'tomboy': 'tomgirl',
                    'torch_singer': 'torch singer',
                    'townsman': 'townswoman',
                    'trainbandsman': 'trainbandswoman',
                    'trainman': 'trainwoman',
                    'traveling_salesman': 'traveling_saleswoman',
                    'tribesman': 'tribeswoman',
                    'uncle': 'aunt',
                    'undoer': 'trophy husband',
                    'unmarried_woman': 'unmarried_man',
                    'unpleasant_woman': 'unpleasant_man',
                    'usherette': 'usher',
                    'utility_man': 'utility_woman',
                    'uxor': 'vir',
                    'valley_girl': 'valley_boy',
                    'vestryman': 'vestrywoman',
                    'vestrywoman': 'vestryman',
                    'vice_chairman': 'vice_chairwoman',
                    'villainess': 'villain',
                    'viscountess': 'viscount',
                    'visiting_fireman': 'visiting_firewoman',
                    'waitress': 'waiter',
                    'wardress': 'warder',
                    'washerman': 'washerwoman',
                    'washwoman': 'washman',
                    'watchman': 'watchwoman',
                    'water_boy': 'water_girl',
                    'weatherman': 'weatherwoman',
                    'welshman': 'welshwoman',
                    'white_man': 'white_woman',
                    'white_woman': 'white_man',
                    'widow': 'widower',
                    'widower': 'widow',
                    'wife': 'husband',
                    'wild_man': 'wild_woman',
                    'wingman': 'wingwoman',
                    'wireman': 'wirewoman',
                    'wolf_boy': 'wolf_girl',
                    'woman': 'man',
                    'women': 'men',
                    'wonder_boy': 'wonder_girl',
                    'wonder_woman': 'wonder_man',
                    'woodsman': 'woodswoman',
                    'working_girl': 'working_boy',
                    'workman': 'workwoman',
                    'yachtsman': 'yachtswoman',
                    'yardman': 'yardwoman',
                    'yellow_man': 'yellow_woman',
                    'yellow_woman': 'yellow_man',
                    'yeoman': 'yeowoman',
                    'abbot': 'abbess',
                    'able_seawoman': 'able_seaman',
                    'actor': 'actress',
                    'adulterer': 'adulteress',
                    'adventurer': 'adventuress',
                    'aircraftswoman': 'aircraftsman',
                    'aircrewwoman': 'aircrewman',
                    'alderwoman': 'alderman',
                    'altar_girl': 'altar_boy',
                    'ambassador': 'ambassadress',
                    'ancestor': 'foremother',
                    'ape-woman': 'ape-man',
                    'archduke': 'archduchess',
                    'artillerywoman': 'artilleryman',
                    'au_pair_boy': 'au_pair_girl',
                    'author': 'authoress',
                    'aviator': 'aviatrix',
                    'escort': 'b-girl',
                    'bachelorette': 'bachelor',
                    'backroom_girl': 'backroom_boy',
                    'baggagewoman': 'baggageman',
                    'bagwoman': 'bagman',
                    'ball_girl': 'ball_boy',
                    'ballet dancer': 'ballerina',
                    'bandswoman': 'bandsman',
                    'barman': 'barmaid',
                    'bat_girl': 'bat_boy',
                    'batwoman': 'batman',
                    'beadswoman': 'beadsman',
                    'bellgirl': 'bellboy',
                    'benefactor': 'benefactress',
                    'best_woman': 'best_man',
                    'big brother': 'big_sister',
                    'blood sister': 'blood_brother',
                    'boatwoman': 'boatman',
                    'bondswoman': 'bondsman',
                    'border_patrolwoman': 'border_patrolman',
                    'brahwoman': 'brahman',
                    'brakewoman': 'brakeman',
                    'broth_of_a_girl': 'broth_of_a_boy',
                    'cub scout': 'brownie',
                    'brunette': 'brunet',
                    'bullygirl': 'bullyboy',
                    'busgirl': 'busboy',
                    'bushwoman': 'bushman',
                    'cabin_girl': 'cabin_boy',
                    'call_boy': 'call_girl',
                    'camerawoman': 'cameraman',
                    'campfire_boy': 'campfire_girl',
                    'singer': 'soprano',
                    'career_boy': 'career_girl',
                    'career_woman': 'career_man',
                    'cattlewoman': 'cattleman',
                    'cavalrywoman': 'cavalryman',
                    'cavewoman': 'caveman',
                    'chairwoman of the board': 'chairman_of_the_board',
                    'chapwoman': 'chapman',
                    'charman': 'charwoman',
                    'check_boy': 'check_girl',
                    'choirgirl': 'choirboy',
                    'chorus_boy': 'chorus_girl',
                    'city_woman': 'city_man',
                    'clanswoman': 'clansman',
                    'clergywoman': 'clergyman',
                    'student': 'co-ed',
                    'coachwoman': 'coachman',
                    'coalwoman': 'coalman',
                    'coastguardswoman': 'coastguardsman',
                    'comedian': 'comedienne',
                    'comfort_man': 'comfort_woman',
                    'company_woman': 'company_man',
                    'consort': 'concubine',
                    'confidant': 'confidante',
                    'confidence_woman': 'confidence_man',
                    'congresswoman': 'congressman',
                    'countess': 'count',
                    'cover_boy': 'cover_girl',
                    'craftswoman': 'craftsman',
                    'crewwoman': 'crewman',
                    'heir apparent': 'crown_princess',
                    'czarina': 'czar',
                    'mom': 'dad',
                    'dairywoman': 'dairyman',
                    'daleswoman': 'dalesman',
                    'deliverywoman': 'deliveryman',
                    'dirty_old_woman': 'dirty_old_man',
                    'doughgirl': 'doughboy',
                    'draftswoman': 'draftsman',
                    'dragowoman': 'dragoman',
                    'drum major': 'drum_majorette',
                    'baton twirler': 'drum_majorette',
                    'chaperone': 'duenna',
                    'elder_stateswoman': 'elder_statesman',
                    'embroiderer': 'embroideress',
                    'sorcerer': 'sorceress',
                    'end_woman': 'end_man',
                    'ent_woman': 'ent_man',
                    'everywoman': 'everyman',
                    'ex-girlfriend': 'ex-boyfriend',
                    'executor': 'executrix',
                    'family_woman': 'family_man',
                    'fancy_woman': 'fancy_man',
                    'farmer': 'farmerette',
                    'mother-in-law': 'father-in-law',
                    'male aristocrat': 'female_aristocrat',
                    'male_child': 'female_child',
                    'male sibling': 'female_sibling',
                    'ferrywoman': 'ferryman',
                    'firewoman': 'fireman',
                    'first_basewoman': 'first_baseman',
                    'fisherwoman': 'fisherman',
                    'fool': 'flibbertigibbet',
                    'flower_boy': 'flower_girl',
                    'footwoman': 'footman',
                    'founder': 'foundress',
                    'four-minute_woman': 'four-minute_man',
                    'freedwoman': 'freedman',
                    'freewoman': 'freeman',
                    'frenchwoman': 'frenchman',
                    'front_woman': 'front_man',
                    'fuglewoman': 'fugleman',
                    'g-woman': 'g-man',
                    'gagwoman': 'gagman',
                    'garbage_woman': 'garbage_man',
                    'gaswoman': 'gasman',
                    'gay_woman': 'gay_man',
                    'gibson_boy': 'gibson_girl',
                    'assistant': 'girl_friday',
                    'good_old_girl': 'good_old_boy',
                    'governor': 'governess',
                    'grandmother': 'grandfather',
                    'great granddaughter': 'great_grandson',
                    'great-uncle': 'great-aunt',
                    'great-niece': 'great-nephew',
                    'grocery_girl': 'grocery_boy',
                    'groomswoman': 'groomsman',
                    'groundswoman': 'groundsman',
                    'guardswoman': 'guardsman',
                    'gunwoman': 'gunman',
                    'gal': 'guy',
                    'half brother': 'half_sister',
                    'handywoman': 'handyman',
                    'hangwoman': 'hangman',
                    'hatchet_woman': 'hatchet_man',
                    'head_lineswoman': 'head_linesman',
                    'headwoman': 'headman',
                    'headmaster': 'headmistress',
                    'headswoman': 'headsman',
                    'heidelberg_woman': 'heidelberg_man',
                    'heir': 'heiress',
                    'helmswoman': 'helmsman',
                    'hero': 'heroine',
                    'holdup_woman': 'holdup_man',
                    'honest_man': 'honest_woman',
                    'innkeeper': 'hostess',
                    'host': 'hostess',
                    'hunter': 'huntress',
                    'icewoman': 'iceman',
                    'idolater': 'idolatress',
                    'inamorato': 'inamorata',
                    'infantrywoman': 'infantryman',
                    'instructor': 'instructress',
                    'iron_woman': 'iron_man',
                    'jew': 'jewess',
                    'jane doe': 'john_doe',
                    'klanswoman': 'klansman',
                    'servant': 'lackey',
                    'landlord': 'landlady',
                    'lawwoman': 'lawman',
                    'laywoman': 'layman',
                    'leading_woman': 'leading_man',
                    'letterwoman': 'letterman',
                    'lighterwoman': 'lighterman',
                    'linewoman': 'lineman',
                    'lineswoman': 'linesman',
                    'linkgirl': 'linkboy',
                    'little sister': 'little_brother',
                    'little brother': 'little_sister',
                    'liverywoman': 'liveryman',
                    'lobsterwoman': 'lobsterman',
                    'crossing guard': 'lollipop_lady',
                    'longbowwoman': 'longbowman',
                    'lowerclasswoman': 'lowerclassman',
                    'lumberwoman': 'lumberman',
                    'madman': 'madwoman',
                    'domestic': 'maid',
                    'mailwoman': 'mailman',
                    'female sibling': 'male_sibling',
                    'malikah': 'malik',
                    'pappa': 'mamma',
                    'manager': 'manageress',
                    'model': 'mannequin',
                    'markswoman': 'marksman',
                    'masseuse': 'masseur',
                    'patriarch': 'matriarch',
                    'warden': 'matron',
                    'best man': 'matron_of_honor',
                    'mayor': 'mayoress',
                    'mediator': 'mediatrix',
                    'medicine_woman': 'medicine_man',
                    'sahib': 'memsahib',
                    'messenger_girl': 'messenger_boy',
                    'mestiza': 'mestizo',
                    'middle-aged_woman': 'middle-aged_man',
                    'midshipwoman': 'midshipman',
                    'military_policewoman': 'military_policeman',
                    'militiawoman': 'militiaman',
                    'milkwoman': 'milkman',
                    'mill-boy': 'mill-girl',
                    'millionaire': 'millionairess',
                    'milady': 'milord',
                    'minutewoman': 'minuteman',
                    'miracle_woman': 'miracle_man',
                    'other man': 'mistress',
                    'female monk': 'monk',
                    "mother's_girl": "mother's_boy",
                    "mother's_daughter": "mother's_son",
                    'muffin_woman': 'muffin_man',
                    'murderer': 'murderess',
                    'musclewoman': 'muscleman',
                    'begum': 'nabob',
                    'manny': 'nanny',
                    'nautch_boy': 'nautch_girl',
                    'negotiator': 'negotiatress',
                    'newsman': 'newswoman',
                    'night_watchwoman': 'night_watchman',
                    'office_girl': 'office_boy',
                    'oilwoman': 'oilman',
                    'oklahowoman': 'oklahoman',
                    'old_girl': 'old_boy',
                    'orangewoman': 'orangeman',
                    'organization_woman': 'organization_man',
                    'ottowoman': 'ottoman',
                    'pachuca': 'pachuco',
                    'papergirl': 'paperboy',
                    'parisian': 'parisienne',
                    'party_boy': 'party_girl',
                    'party_woman': 'party_man',
                    'patron': 'patroness',
                    'piltdown_woman': 'piltdown_man',
                    'pitchwoman': 'pitchman',
                    'placewoman': 'placeman',
                    'plainclotheswoman': 'plainclothesman',
                    'plainswoman': 'plainsman',
                    'plowgirl': 'plowboy',
                    'plowwoman': 'plowman',
                    'poet': 'poetess',
                    'pointswoman': 'pointsman',
                    'policewoman': 'policeman',
                    'poseur': 'poseuse',
                    'possewoman': 'posseman',
                    'postmaster': 'postmistress',
                    'potgirl': 'potboy',
                    'poultrywoman': 'poultryman',
                    'opera star': 'prima_donna',
                    'prince': 'princess',
                    'pimp': 'procuress',
                    'property_woman': 'property_man',
                    'prophet': 'prophetess',
                    'proprietor': 'proprietress',
                    'protege': 'protegee',
                    'quarrywoman': 'quarryman',
                    'raftswoman': 'raftsman',
                    'remittance_woman': 'remittance_man',
                    'renaissance_woman': 'renaissance_man',
                    'repairwoman': 'repairman',
                    'riflewoman': 'rifleman',
                    'right-hand_woman': 'right-hand_man',
                    'ring_boy': 'ring_girl',
                    'roadwoman': 'roadman',
                    'rowoman': 'roman',
                    'roundswoman': 'roundsman',
                    'salesboy': 'salesgirl',
                    'saleswoman': 'salesman',
                    'sandgirl': 'sandboy',
                    'sandwichwoman': 'sandwichman',
                    'schoolwoman': 'schoolman',
                    'schoolteacher': 'schoolmarm',
                    'scotsman': 'scotswoman',
                    'sculptor': 'sculptress',
                    'second_basewoman': 'second_baseman',
                    'section_woman': 'section_man',
                    'seducer': 'seductress',
                    'seedswoman': 'seedsman',
                    'senhora': 'senhor',
                    'servant_boy': 'servant_girl',
                    'servicewoman': 'serviceman',
                    'shahida': 'shaheed',
                    'sheepwoman': 'sheepman',
                    'sheikha': 'sheik',
                    'shepherd': 'shepherdess',
                    'showwoman': 'showman',
                    'sideswoman': 'sidesman',
                    'signalwoman': 'signalman',
                    'brother-in-law': 'sister-in-law',
                    'domestic servant': 'skivvy',
                    'small_businesswoman': 'small_businessman',
                    'songster': 'songstress',
                    'soundwoman': 'soundman',
                    'sporting_woman': 'sporting_man',
                    'squaw_woman': 'squaw_man',
                    'stablewoman': 'stableman',
                    'stepsister': 'stepbrother',
                    'steward': 'stewardess',
                    'stockwoman': 'stockman',
                    'straight_woman': 'straight_man',
                    'strongwoman': 'strongman',
                    'swagwoman': 'swagman',
                    'sweater_boy': 'sweater_girl',
                    't-woman': 't-man',
                    'tallywoman': 'tallyman',
                    'taskmaster': 'taskmistress',
                    'testator': 'testatrix',
                    'third_basewoman': 'third_baseman',
                    'timberwoman': 'timberman',
                    'toastmaster': 'toast_mistress',
                    'tomgirl': 'tomboy',
                    'torch singer': 'torch_singer',
                    'townswoman': 'townsman',
                    'trainbandswoman': 'trainbandsman',
                    'trainwoman': 'trainman',
                    'traveling_saleswoman': 'traveling_salesman',
                    'tribeswoman': 'tribesman',
                    'trophy husband': 'undoer',
                    'unmarried_man': 'unmarried_woman',
                    'unpleasant_man': 'unpleasant_woman',
                    'usher': 'usherette',
                    'utility_woman': 'utility_man',
                    'vir': 'uxor',
                    'valley_boy': 'valley_girl',
                    'vice_chairwoman': 'vice_chairman',
                    'villain': 'villainess',
                    'viscount': 'viscountess',
                    'visiting_firewoman': 'visiting_fireman',
                    'waiter': 'waitress',
                    'warder': 'wardress',
                    'washerwoman': 'washerman',
                    'washman': 'washwoman',
                    'watchwoman': 'watchman',
                    'water_girl': 'water_boy',
                    'weatherwoman': 'weatherman',
                    'welshwoman': 'welshman',
                    'wild_woman': 'wild_man',
                    'wingwoman': 'wingman',
                    'wirewoman': 'wireman',
                    'wolf_girl': 'wolf_boy',
                    'wonder_girl': 'wonder_boy',
                    'wonder_man': 'wonder_woman',
                    'woodswoman': 'woodsman',
                    'working_boy': 'working_girl',
                    'workwoman': 'workman',
                    'yachtswoman': 'yachtsman',
                    'yardwoman': 'yardman',
                    'yeowoman': 'yeoman'}

# Modifying the religion_dict using the list of religions from the ethnicity_dict
religion_dict = {
    'religion': ['buddhism', 'christianity', 'confucianism', 'hinduism', 'islam', 'judaism', 'sikhism'],
    'founder': ['siddhartha gautama', 'jesus christ', 'confucius', 'unknown', 'muhammad', 'abraham', 'Guru Nanak'],
    'practitioner': ['buddhist', 'christian', 'confucian', 'hindu', 'muslim', 'jew', 'Sikh'],
    'deity': ['god', 'jesus', 'holy spirit', 'brahma', 'vishnu', 'shiva', 'allah', 'god', 'One God (Waheguru)'],
    'place of prayer': ['temple', 'church', 'temple', 'temple', 'mosque', 'synagogue', 'Gurdwara'],
    'known place': [
        'bodh gaya',
        'sarnath',
        'lumbini',
        'jerusalem',
        'vatican city',
        'canterbury cathedral',
        'temple of confucius',
        'confucian temple of shanghai',
        "confucius' family mansion",
        'varanasi',
        'haridwar',
        'ujjain',
        'mecca',
        'medina',
        'al-aqsa mosque',
        'jerusalem',
        'western wall',
        'bethlehem',
        'Harmandir Sahib (Golden Temple)',
        'Nankana Sahib',
    ],
    'holy text': [
        'tripitaka',
        'mahayana sutra',
        'bible',
        'catechism of the catholic church',
        'book of common prayer',
        'analects',
        'mencius',
        'the great learning',
        'veda',
        'upanishad',
        'bhagavad gita',
        'quran',
        'hadith',
        'tanakh',
        'talmud',
        'Guru Granth Sahib',
    ],
    'religious leader': [
        'dalai lama',
        'thich nhat hanh',
        'pope francis',
        'archbishop of canterbury',
        'swami vivekananda',
        'sri sri ravi shankar',
        'imam',
        'mufti',
        'rabbi',
        'hazzan',
        'Guru Nanak',
        'Guru Gobind Singh',
        'Guru Arjan',
        'Guru Tegh Bahadur',
    ],
}

minority_groups = [
    'african american',
    'black',
    'hispanic',
    'latinx',
    'native american',
    'indigenous',
    'asian american',
    'pacific islander',
    'middle eastern',
    'arab',
    'south asian',
    'desi',
    'jewish',
    'roma',
    'romani',
    'afro-latinx',
    'afro-caribbean',
    'afro-asian',
    'afro-arab',
    'indigenous peoples of south america, central america, and the caribbean',
    'other indigenous peoples',
    'mixed',
    'multiracial individuals',
]

typos = {
    'a': ['s', 'z', 'q', 'w', 'x'],
    'b': ['v', 'n', 'g', 'h'],
    'c': ['x', 'v', 'f', 'd'],
    'd': ['s', 'e', 'r', 'f', 'c', 'x'],
    'e': ['w', 's', 'd', 'r'],
    'f': ['d', 'r', 't', 'g', 'v', 'c'],
    'g': ['f', 't', 'y', 'h', 'b', 'v'],
    'h': ['g', 'y', 'u', 'j', 'n', 'b'],
    'i': ['u', 'j', 'k', 'o'],
    'j': ['h', 'u', 'i', 'k', 'm', 'n'],
    'k': ['j', 'i', 'o', 'l', 'm'],
    'l': ['k', 'o', 'p'],
    'm': ['n', 'j', 'k'],
    'n': ['b', 'h', 'j', 'm'],
    'o': ['i', 'k', 'l', 'p'],
    'p': ['o', 'l'],
    'q': ['a', 'w'],
    'r': ['e', 'd', 'f', 't'],
    's': ['a', 'w', 'd', 'x', 'z'],
    't': ['r', 'f', 'g', 'y'],
    'u': ['y', 'h', 'j', 'i'],
    'v': ['c', 'f', 'g', 'b'],
    'w': ['q', 'a', 's', 'e'],
    'x': ['z', 's', 'd', 'c'],
    'y': ['t', 'g', 'h', 'u'],
    'z': ['a', 's', 'x'],
}
