name: Build ML Worker Docker image and push to registry with dev tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@master

      - name: "Append ARM buildx builder from AWS"
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: ssh://${{ secrets.ARM_SSH_CONNECTION_STRING }}
          ssh_private_key: ${{ secrets.ARM_SSH_PRIVATE_KEY }}


      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker registry
        uses: docker/login-action@v2
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        with:
          username: giskardai
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        env:
          TAG: dev
        with:
          push: ${{ steps.extract_branch.outputs.branch == 'main' }}
          set: |
            *.platform=linux/amd64
            *.platform=linux/arm64
      

      - name: Invoke deployment hook
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        run: |
          curl -L --silent --max-time 900 ${{ secrets.TEST_SERVER_WEBHOOK_URL_BASE }}/redeploy-dev

      - name: Remove containers and volumes
        run: |
          docker system prune -a -f
          docker builder prune --force --keep-storage=10GB


