name: Python install

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('pdm.lock')}}
          restore-keys: ${{ runner.os }}-venv-${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Make
        run: make

      - name: Replace local coverage.xml path by docker path for Sonar
        run: sed -i 's/\/home\/runner\/work\/python-client\/python-client\//\/github\/workspace\//g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Extract current package version
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'project.version'

      - name: Get current date
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        id: current_date
        env:
          TZ: Europe/Paris
        run: echo "CURRENT_DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set dev version
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "pyproject.toml"
          key: "project.version"
          value: '${{ steps.read_toml.outputs.value }}.dev${{ steps.current_date.outputs.CURRENT_DATE }}'

      - name: Build dev version
        run: |
          make build

      - name: Archive built artifacts
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        uses: actions/upload-artifact@v3
        with:
          name: giskard-dev-${{ matrix.python-version }}.whl
          path: dist/*whl

