"""add target_feature to table feedbacks

Revision ID: 1d23c3b2ac17
Revises: 5fddce341c39
Create Date: 2021-08-31 17:46:42.687834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d23c3b2ac17'
down_revision = '5fddce341c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('target_feature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'target_feature')
    # ### end Alembic commands ###
