name: Backend
on:
  push:
    branches:
      - main
  pull_request:
    # https://docs.github.com/fr/actions/using-workflows/workflow-syntax-for-github-actions#exemple--inclusion-de-chemins-dacc%C3%A8s
    paths-ignore:
      - 'python-client/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "$(du -sh $(ls -A ~) 2>/dev/null | sort -hr)"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Setup Gradle # To cache ~/.gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Cache Frontend dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json')}}
          restore-keys: ${{ runner.os }}-frontend

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build frontend
        env:
          GSK_DISABLE_ANALYTICS: True
        run: ./gradlew :frontend:build
  
      - name: Build & test backend
        env:
          GSK_DISABLE_ANALYTICS: True
        run: ./gradlew :backend:build :backend:test :backend:integrationTest :backend:jacocoTestReport --info --parallel

      - run: echo "$(du -sh $(ls -A ~) 2>/dev/null | sort -hr)"
