name: Pre-commit checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GSK_DISABLE_ANALYTICS: true
  SENTRY_ENABLED: false
  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
defaults:
  run:
    shell: bash
jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0
